{
    "type": "bundle",
    "id": "bundle--f2bc651d-e6af-4b0f-8225-6c6885863b07",
    "spec_version": "2.0",
    "objects": [
        {
            "type": "relationship",
            "target_ref": "attack-pattern--63b6942d-8359-4506-bfb3-cf87aa8120ee",
            "description": "Several transportation organizations in Ukraine have suffered from being infected by [Bad Rabbit](https://collaborate.mitre.org/attackics/index.php/Software/S0005), resulting in some computers becoming encrypted, according to media reports. (Citation: ESET Bad Rabbit Oct 2017)",
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "created": "2017-05-31T21:33:27.074Z",
            "id": "relationship--d7ea83fa-87c7-4d36-96d5-aee554504040",
            "source_ref": "malware--2eaa5319-5e1e-4dd7-bbc4-566fced3964a",
            "modified": "2020-01-02T00:14:20.652Z",
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "external_references": [
                {
                    "source_name": "ESET Bad Rabbit Oct 2017",
                    "description": "Marc-Etienne M.L\u00e9veill\u00e9. (2017, October 24). Bad Rabbit: Not\u2011Petya is back with improved ransomware. Retrieved October 27, 2019.",
                    "url": "https://www.welivesecurity.com/2017/10/24/bad-rabbit-not-petya-back/"
                }
            ],
            "relationship_type": "uses"
        }
    ]
}